# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wolfcastle < Formula
  desc "Wolfcastle takes complex work, breaks it into pieces, and sends AI models to destroy every one of them"
  homepage "https://github.com/dorkusprime/wolfcastle"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.4.2/wolfcastle_0.4.2_darwin_amd64.tar.gz"
      sha256 "d5be4f5da45356e84df6cc8511162c2d34e292c4490119a23d302f46a96e359a"

      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.4.2/wolfcastle_0.4.2_darwin_arm64.tar.gz"
      sha256 "b1a73946969195275d9806e549e0550891a11eeefbb962753b09d80f7257dd0b"

      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.4.2/wolfcastle_0.4.2_linux_amd64.tar.gz"
      sha256 "d6fc5e619ff50d768e76eb192cd3af4be0b59409a4d6515ccf31badceaf47419"
      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.4.2/wolfcastle_0.4.2_linux_arm64.tar.gz"
      sha256 "ece0b595955cd97ca763637bde22676e6cec0d5e8c486d8377a3aa6a6d3b9f5a"
      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
  end

  test do
    system "#{bin}/wolfcastle", "version"
  end
end
