# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wolfcastle < Formula
  desc "Wolfcastle takes complex work, breaks it into pieces, and sends AI models to destroy every one of them"
  homepage "https://github.com/dorkusprime/wolfcastle"
  version "0.1.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.1.0-rc.1/wolfcastle_0.1.0-rc.1_darwin_amd64.tar.gz"
      sha256 "7a438fd232dfdd658739b575698b1028646b49b4f40db56ff9e95fd1954966a4"

      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.1.0-rc.1/wolfcastle_0.1.0-rc.1_darwin_arm64.tar.gz"
      sha256 "c56043fed65b52d8509f28e566e04d56d8007dbc7e871d15bffbe67892fec5ab"

      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.1.0-rc.1/wolfcastle_0.1.0-rc.1_linux_amd64.tar.gz"
      sha256 "f6556c571c89d7a20a102baf2439c7f71607c684227adbc79fe35e2b3d9c33d2"
      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.1.0-rc.1/wolfcastle_0.1.0-rc.1_linux_arm64.tar.gz"
      sha256 "5198d57d903e8dc5e4da4dc7b02bb68bf0864d01ec5487e7e8993588f559e167"
      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
  end

  test do
    system "#{bin}/wolfcastle", "version"
  end
end
