# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WolfcastleAT0_6 < Formula
  desc "Wolfcastle takes complex work, breaks it into pieces, and sends AI models to destroy every one of them"
  homepage "https://github.com/dorkusprime/wolfcastle"
  version "0.6.4"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.6.4/wolfcastle_0.6.4_darwin_amd64.tar.gz"
      sha256 "db645fdfae510a81d2a743bb8705eb9044acbd2ce74ce5aea4278b1998e1e60c"

      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.6.4/wolfcastle_0.6.4_darwin_arm64.tar.gz"
      sha256 "8fae7db31eac7ae65027f78e22a732bc090aa002152d8817203a4cebda2a5485"

      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.6.4/wolfcastle_0.6.4_linux_amd64.tar.gz"
      sha256 "4b5a102115f0a0ce79a1ab630dd489c3c63d2ae61554fd8791c25950be228a9a"
      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dorkusprime/wolfcastle/releases/download/v0.6.4/wolfcastle_0.6.4_linux_arm64.tar.gz"
      sha256 "0b97f735d5b7983bcf4d9b4853ee79584feb0905330b791e28e7cd2d929bc0e3"
      define_method(:install) do
        bin.install "wolfcastle"
      end
    end
  end

  test do
    system "#{bin}/wolfcastle", "version"
  end
end
